apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: prom-pv-claim
    labels:
        app: prom
        env: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
