apiVersion: v1
kind: Service
metadata:
  name: prom
  labels:
    app: prom
spec:
  selector:
    app: prom
    env: prod
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30032
