apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: grafana-pv-claim
    labels:
        app: grafana
        env: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
